#include "PluginProcessor.h"
#include "PluginEditor.h"

#if JUCE_WEB_BROWSER
  #include <juce_gui_extra/juce_gui_extra.h>
  #if PLUGIN_USE_WEB_UI
    #include "PluginUIData.h"   // generated by juce_add_binary_data
  #endif
#endif

// ── Helpers ───────────────────────────────────────────────────────────────────

#if JUCE_WEB_BROWSER && PLUGIN_USE_WEB_UI
static juce::String mimeTypeForPath (const juce::String& path)
{
    if (path.endsWith (".html"))  return "text/html";
    if (path.endsWith (".js"))    return "application/javascript";
    if (path.endsWith (".css"))   return "text/css";
    if (path.endsWith (".svg"))   return "image/svg+xml";
    if (path.endsWith (".png"))   return "image/png";
    if (path.endsWith (".woff2")) return "font/woff2";
    return "application/octet-stream";
}

// Serve files embedded by juce_add_binary_data (PluginUIData namespace).
static std::optional<juce::WebBrowserComponent::Resource>
serveEmbeddedFile (const juce::String& url)
{
    auto path = url.trimCharactersAtStart ("/");

    // Root request → serve index.html
    if (path.isEmpty())
        path = "index.html";

    // JUCE binary data strips directories, so match on filename only
    auto filename = path.fromLastOccurrenceOf ("/", false, false);
    if (filename.isEmpty())
        filename = path;

    // Look up by original filename to avoid replicating JUCE's name-mangling
    int size = 0;
    const char* data = nullptr;

    for (int i = 0; i < PluginUIData::namedResourceListSize; ++i)
    {
        if (filename == juce::String (PluginUIData::originalFilenames[i]))
        {
            data = PluginUIData::getNamedResource (PluginUIData::namedResourceList[i], size);
            break;
        }
    }

    if (data == nullptr)
        return std::nullopt;

    auto mime = mimeTypeForPath (filename);

    std::vector<std::byte> bytes ((size_t) size);
    std::memcpy (bytes.data(), data, (size_t) size);

    return juce::WebBrowserComponent::Resource { std::move (bytes), mime };
}
#endif

// ── Editor ────────────────────────────────────────────────────────────────────

MyPluginNameAudioProcessorEditor::MyPluginNameAudioProcessorEditor (MyPluginNameAudioProcessor& p)
    : AudioProcessorEditor (&p), audioProcessor (p)
{
    setSize (400, 300);
}

MyPluginNameAudioProcessorEditor::~MyPluginNameAudioProcessorEditor() {}

void MyPluginNameAudioProcessorEditor::paint (juce::Graphics& g)
{
#if JUCE_WEB_BROWSER
    // WebBrowserComponent covers the whole window; nothing to paint here.
    g.fillAll (juce::Colours::black);
#else
    g.fillAll (getLookAndFeel().findColour (juce::ResizableWindow::backgroundColourId));
    g.setColour (juce::Colours::white);
    g.setFont (15.0f);
    g.drawFittedText ("My Plugin Name", getLocalBounds(), juce::Justification::centred, 1);
#endif
}

void MyPluginNameAudioProcessorEditor::resized()
{
#if JUCE_WEB_BROWSER
    if (webBrowser == nullptr)
    {
        // Create WebView lazily — ensures component has a native peer
        auto options = juce::WebBrowserComponent::Options{}
            .withNativeIntegrationEnabled()
            // Uncomment and add relays once you have parameters:
            // .withOptionsFrom (gainRelay)
      #if PLUGIN_USE_WEB_UI
            .withResourceProvider (serveEmbeddedFile,
                                   juce::String { "https://juce.localhost" })
      #endif
            ;

        webBrowser = std::make_unique<juce::WebBrowserComponent> (options);
        addAndMakeVisible (*webBrowser);

      #if defined(DEBUG) || defined(_DEBUG)
        webBrowser->goToURL ("http://localhost:5173");
      #elif PLUGIN_USE_WEB_UI
        webBrowser->goToURL (juce::WebBrowserComponent::getResourceProviderRoot());
      #endif
    }

    webBrowser->setBounds (getLocalBounds());
#endif
}
