#include "PluginProcessor.h"
#include "PluginEditor.h"

#if JUCE_WEB_BROWSER
  #include <juce_gui_extra/juce_gui_extra.h>
  #if PLUGIN_USE_WEB_UI
    #include "PluginUIData.h"   // generated by juce_add_binary_data
  #endif
#endif

// ── Helpers ───────────────────────────────────────────────────────────────────

#if JUCE_WEB_BROWSER && PLUGIN_USE_WEB_UI
static juce::String mimeTypeForPath (const juce::String& path)
{
    if (path.endsWith (".html"))  return "text/html";
    if (path.endsWith (".js"))    return "application/javascript";
    if (path.endsWith (".css"))   return "text/css";
    if (path.endsWith (".svg"))   return "image/svg+xml";
    if (path.endsWith (".png"))   return "image/png";
    if (path.endsWith (".woff2")) return "font/woff2";
    return "application/octet-stream";
}

// Serve files embedded by juce_add_binary_data (PluginUIData namespace).
static std::optional<juce::WebBrowserComponent::Resource>
serveEmbeddedFile (const juce::String& url)
{
    // url arrives as "/index.html" or "/assets/main-abc123.js" etc.
    // BinaryData resource names use underscores and strip the path prefix.
    auto resourceName = url.trimCharactersAtStart ("/").replaceCharacter ('/', '_').replaceCharacter ('-', '_').replaceCharacter ('.', '_');

    int size = 0;
    const char* data = PluginUIData::getNamedResource (resourceName.toRawUTF8(), size);

    if (data == nullptr)
        return std::nullopt;

    std::vector<std::byte> bytes (size);
    std::memcpy (bytes.data(), data, (size_t) size);

    return juce::WebBrowserComponent::Resource { std::move (bytes), mimeTypeForPath (url) };
}
#endif

// ── Editor ────────────────────────────────────────────────────────────────────

MyPluginNameAudioProcessorEditor::MyPluginNameAudioProcessorEditor (MyPluginNameAudioProcessor& p)
    : AudioProcessorEditor (&p), audioProcessor (p)
{
    setSize (400, 300);

#if JUCE_WEB_BROWSER
    auto options = juce::WebBrowserComponent::Options{}
        .withNativeIntegrationEnabled()
        // Uncomment and add relays once you have parameters:
        // .withOptionsFrom (gainRelay)
  #if PLUGIN_USE_WEB_UI
        .withResourceProvider (serveEmbeddedFile,
                               juce::URL { "https://juce.localhost/" })
  #endif
        ;

    webBrowser = std::make_unique<juce::WebBrowserComponent> (options);
    addAndMakeVisible (*webBrowser);

  #if defined(DEBUG) || defined(_DEBUG)
    // Hot-reload from Vite dev server: run `npm run dev` in the ui/ directory.
    webBrowser->goToURL ("http://localhost:5173");
  #elif PLUGIN_USE_WEB_UI
    webBrowser->goToURL (juce::WebBrowserComponent::getResourceProviderRoot());
  #endif
#endif
}

MyPluginNameAudioProcessorEditor::~MyPluginNameAudioProcessorEditor() {}

void MyPluginNameAudioProcessorEditor::paint (juce::Graphics& g)
{
#if JUCE_WEB_BROWSER
    // WebBrowserComponent covers the whole window; nothing to paint here.
    g.fillAll (juce::Colours::black);
#else
    g.fillAll (getLookAndFeel().findColour (juce::ResizableWindow::backgroundColourId));
    g.setColour (juce::Colours::white);
    g.setFont (15.0f);
    g.drawFittedText ("My Plugin Name", getLocalBounds(), juce::Justification::centred, 1);
#endif
}

void MyPluginNameAudioProcessorEditor::resized()
{
#if JUCE_WEB_BROWSER
    if (webBrowser != nullptr)
        webBrowser->setBounds (getLocalBounds());
#endif
}
